spring:
    application:
        name: vroom

    datasource:
        url: jdbc:mysql://localhost:3306/vroom?serverTimezone=Asia/Seoul
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: '0000'

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: Asia/Seoul

    jackson:
        time-zone: Asia/Seoul

jwt:
    secret-key: ${JWT_SECRET_KEY:dDZQMmd6RkhQbnZhM210dDl6QW1vSncxb2U0S2Njd2Q=}
    access-exp: ${JWT_ACCESS_EXP:360000}
    refresh-exp: ${JWT_REFRESH_EXP:86400000}


logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bing: TRACE
        org.springframework.security: DEBUG
        org.springframework: DEBUG
        org.springframework.web.socket: DEBUG
        org.springframework.messaging: DEBUG

